### ISSUE TITLE
Potential race-condition when using mod_realdoc in a threaded/asynchronous environment

### ISSUE THREAD

**Issue by andytson** [etsy/mod_realdoc#4]
r->server is shared between all requests handled by a httpd process on the same VirtualHost (at least in httpd 2.2), therefore changing it in a threaded/asynchronous environment may lead to unexpected race-conditions, where one request has changed the document root after another request has read it for translating to script filename.

mpm_worker - will be affected
mpm_event - I'm unsure how much of the request is handled asynchronously

The scenario that might be possible is:

Request 1: in mod_realdoc post_read_request hook, loads a cached resolved document root
Request 1: runs it's translate_name hooks
Request 2: in mod_realdoc post_read_request hook, finds cache is expired, so saves a new document root entry
Request 2: runs it's translate_name hooks
Request 1: sends the new DOCUMENT_ROOT and old SCRIPT_FILENAME to page processor (e.g. php)
Request 2: sends the new DOCUMENT_ROOT and new SCRIPT_FILENAME to page processor (e.g. php)

The only real solution I believe is to use translate_name to only update the uri to filename handling when in these modes. This wouldn't change the document root however.

**Comment by staabm** [comment]
we would like to use this apache module, but are using mpm event with php (because per sysadmin this is needed for proper http 2.0 support).

is there any known alternative which works with mpm event?
