### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by garak** [etsy/mod_realdoc#8]
As soon as I enable mod_realdoc all my virtual hosts that use a symlinked document root stop to work, giving a 403 error, like the following:

`[Thu May 19 09:00:41.113107 2016] [authz_core:error] [pid 26472] [client 66.249.78.105:51750] AH01630: client denied by server configuration: /full_path/releases/20160506140516/web/app.php`

where `releases/20160506140516` is symlinked from `current` and virtual host has document root pointed to `/full_path/current/web/` and the following configuration:

```
    <Directory "/full_path/current/web">
        Require all granted
    </Directory>
```

Apache is 2.4.20 on Ubuntu 14.04.4

**Comment by garak** [comment]
OK, I found that I needed to grant access to every single release directory.
I resolved using this:
```
<Directory ~ "/full_path/releases/\d{14}/web">
    Require all granted
</Directory>
```

Maybe it's worth to add a note about this in README?

**Comment by hex2a** [comment]
please also note that .htaccess files might stop working if you use regex in the directory path:

> AllowOverride is valid only in <Directory> sections specified without regular expressions, not in \<Location>, \<DirectoryMatch> or \<Files> sections.
https://httpd.apache.org/docs/2.4/en/mod/core.html#allowoverride

**Comment by garak** [comment]
Well, I guess that if you're using .htaccess you don't need a reference to absolute path, so there should be no problem
